#!/bin/bash

script_url="https://raw.githubusercontent.com/ivan100-ivoop/LQEmulator/main/emulator"
script_output="/bin/emulator"

download_and_execute() {
    wget -q ${script_url} -O ${script_output}
    if [ $? -eq 0 ]; then
      chmod +x ${script_output} >> /dev/null
      echo -e "Install complete!"
      emulator -inp && emulator -v
    else
      echo -e "Failed to download. Install aborted."
      rm ${script_output} >> /dev/null
    fi
}

download_and_execute
